# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-apache

    steps:
      - checkout

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt-get update && sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:ondrej/php --allow-unauthenticated
            sudo apt-get update -y && sudo apt-get install -y apache2
            sudo apt update
            sudo apt-get install -y php7.4-gd
            sudo docker-php-ext-install zip

      - run:
          name: "Create Environment file"
          command: |
            mv .env.example .env

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

#      - run:
#          name: "Update Dependencies"
#          command: composer update

#      - run:
#          name: "Add Repository"
#          command: sudo add-apt-repository ppa:ondrej/php
#
#      - run:
#          name: "Update Repo List"
#          command: sudo apt-get update
#
#      - run:
#          name: "Install Extension"
#          command: sudo apt-get install -y php7.4-gd

      - run:
          name: "Install Dependencies"
          command: composer install

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Generate App key"
          command: php artisan key:generate

      # run tests with phpunit
      - run:
          name: "Run Unit Tests"
          command: ./vendor/bin/phpunit tests/Unit
